services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      CLIENT_URL: http://localhost:5173
    volumes:
      - ./server:/app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production
      VITE_API_URL: http://localhost:3001
    volumes:
      - ./client:/app
