services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      CLIENT_URL: http://localhost:5173
    volumes:
      - ./server:/app
      - /app/node_modules  # Volume anonimo per node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"  # Expose port 80 on the host
    environment:
      NODE_ENV: production
      VITE_API_URL: http://localhost:3001
    volumes:
      - ./client:/app
      - /app/node_modules
